-- Create the meeting_records table
create table if not exists meeting_records (
  id bigint generated by default as identity primary key,
  meeting_date date not null,
  content text not null,
  summary text,
  tags text[] default '{}',
  created_at timestamp with time zone default timezone('utc'::text, now()) not null,
  updated_at timestamp with time zone default timezone('utc'::text, now()),
  completed boolean default false,
  completed_at timestamp with time zone,
  archived boolean default false
);

-- Create an index on meeting_date for faster sorting/filtering
create index if not exists meeting_records_date_idx on meeting_records (meeting_date);

-- Enable Row Level Security (RLS)
alter table meeting_records enable row level security;

-- Create a policy that allows all operations for now (adjust as needed for production)
-- Note: If you have authentication, you should restrict this to authenticated users.
create policy "Allow all operations for anon users"
on meeting_records
for all
using (true)
with check (true);
